FROM python:3.7-slim-buster

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

COPY requirements.txt requirements.txt
COPY ./scripts /scripts

# create and activate the virtual environment, and install requirements
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"
RUN pip install pip --upgrade
RUN pip install -r requirements.txt --no-cache-dir

COPY ./scripts /scripts
RUN chmod +x ./scripts*

COPY ./backend /backend
WORKDIR /backend
